name: Workflow tp
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.27.1
      - name: Install dependencies
        run: composer install --prefer-dist
      - name: Run tests
        run: ./vendor/bin/phpunit
            

