name: Mon workflow
on: [push, pull_request]
env:
  VARIABLE_NAME: value
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
      - name: display variable
        run: echo ${{ env.VARIABLE_NAME }}
      - name: Use a Secret
     env:
       SUPER_SECRET: ${{ secrets.SECRET_NAME }}
       run: echo $SUPER_SECRET
